on: push
name: Check Assignment
jobs:
  check-allowed-files:
    runs-on: self-hosted
    container:
      image: ghcr.io/dukestatsci/r_gh_actions:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Check Files
      run: |
        checklist::quit_on_failure({
          checklist::check_allowed_files(c("hw-03.qmd", "hw-03.Rproj", "README.md", "data/*", "images/*"))
        })
      shell: Rscript {0}

  check-renders:
    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}
    runs-on: self-hosted
    container:
      image: ghcr.io/dukestatsci/r_gh_actions:latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install Missing Packages
      run: |
        missing = checklist::install_missing_pkgs(dir = "./", glob = "hw-03.qmd")
      shell: Rscript {0}
    - name: Check Renders
      run: |
        checklist::check_qmd_renders("hw-03.qmd")
      shell: Rscript {0}
    - name: Create artifacts
      uses: actions/upload-artifact@v2
      with:
        name: hw-03-html
        path: hw-03.html
